module 3 task 1
htmlacademy-animation/18428-magic-vacation-1 pull request #7
Opened 2021-03-21 14:34 UTC by juliaross

2021-03-22 20:12 UTC, dean992008 requested changes

2021-03-22 20:12 UTC, dean992008 commented on source/img/prize1.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 350 330">
Анимация не совсем соответсветствует заданию, пересмотрите видео покадрово(можно задать мышку на таймлайне и двигать по кадру). Кресло должно появляться резче, а дирежаблю почти срузу исчезнуть, этого можно добится изменив изинги анимации. Также у лыж должен быть эффект "Доводка и захлёст действия". 
https://www.youtube.com/watch?v=4OxphYV8W3E&t=20s

2021-03-22 20:12 UTC, dean992008 commented on source/js/script.js
> +document.querySelector(`.js-menu-link[href="#prizes"]`).addEventListener(`click`, () => {
Мне не очень нравится это решение. Мне кажеттся вместо это js правильнее использовать loading="lazy" на картинку.

2021-03-22 20:12 UTC, dean992008 commented on source/img/prize1.svg
> +        <animate
Атрибут `animate` продублирован 2 раза, по-моему 1 можно удалить.

2021-03-28 18:59 UTC, gkarev commented
**Привет!** Отличная работа, но все же есть пару замечаний)

1. Анимация вращения дирижабля. Если обратить внимание на видео-референс, можно заменить, что он не просто вращается, а делает это как бы покачиваясь, то есть ускорение не линейное, а ease-in-out, ускоряется, а затем чуть замедляется. Сейчас же он просто вертится туда-сюда)
2. Анимация неба. Сейчас она исчезает одновременно, и появляется тоже, а должна сначала одна, потом вторая. Рекомендую посмотреть внимательно на видео-ряд, что бы зафиксировать тайминги, и более точно внести правки в код. Вам нужно подгадать нужный момент, появления и скрытия элементов)
3. Анимация окон (внутри корзины). Если взглянуть на видео-пример, видно, что окна (маленькие) немного изменяются при покачивании, то есть присутствует морфинг, или трансформация. А вот большое окно, напротив, остается практически статичным, смещаясь разве что вверх, но в текущей реализации, оно раздувается)

2021-03-29 18:26 UTC, merged